### ISSUE TITLE
model request

### ISSUE THREAD

**Issue by Vandermode** [yangj1e/bdn-refremv#3]
Hi, could you share the pretrained model using the synthetic data in CEILNet?
Besides, could you release the code about the data synthetic pipeline since I cannot assure my implementation is correct, i.e. 
```
 A Gaussian blur kernel of standard deviation
σ ∈ [0, 2] is applied on the reflection patch to simulate the defocus blur may appear
on the reflection layer in reality. The two patches are blended using scale weight α ∈
[0.6, 0.8].
```

Thanks.

**Comment by yangj1e** [comment]
The model: https://drive.google.com/open?id=1_inrwkeabPe297gjUQ3SFEaByURKpgpU
