### ISSUE TITLE
How's about the training code and dataset?

### ISSUE THREAD

**Issue by leftthomas** [yangj1e/bdn-refremv#4]
When I look your paper, I find the dataset generation is not clear, so I wonder know how you generate the training images and testing images? And could you just provide a download link about the used training images and testing images, because if someone want to follow your work, they want to compare with the same data, but if you won't provide, then how can they compare with your work?

**Comment by zzhanghub** [comment]
Could you release the code for the training part? :smiley:

**Comment by veronica1428** [comment]
Hey hi, 
Can you please release the code for training ?  
Inanticipation for your response. 

Regards
Veronica

**Comment by yangj1e** [comment]
Hi, as we are doing some subsequent research, the training code will be released afterwards.
